"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from dotenv import load_dotenv
try:
    import certifi
except ImportError:  # pragma: no cover
    certifi = None

if certifi:
    os.environ.setdefault("SSL_CERT_FILE", certifi.where())

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name, default=""):
    value = os.getenv(name)
    if value is None or not value.strip():
        value = default
    return [item.strip() for item in value.split(",") if item.strip()]


def _env_int(name, default=0):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    try:
        return int(value.strip())
    except ValueError:
        return default


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-90096l*g+*q-rvfq0tq$2t$7p+lq#w+ro@y2%!scc_#)z+i%#a")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", True)

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=not DEBUG),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Almaty'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

LOGIN_URL = '/admin/login/'
LOGIN_REDIRECT_URL = '/'

CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,http://localhost:5175,http://127.0.0.1:5175",
)

# In local development, frontend may be opened via LAN IP (e.g. 192.168.x.x:5173).
# Allow all origins in DEBUG to avoid browser-side "Network Error" from blocked CORS.
CORS_ALLOW_ALL_ORIGINS = _env_bool("CORS_ALLOW_ALL_ORIGINS", DEBUG)

# Required so browsers send/receive httpOnly cookies for patient trusted-device login.
CORS_ALLOW_CREDENTIALS = _env_bool("CORS_ALLOW_CREDENTIALS", True)

# With credentials, browsers reject wildcard ACAO; disable allow-all and rely on CORS_ALLOWED_ORIGINS.
if CORS_ALLOW_CREDENTIALS and CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOW_ALL_ORIGINS = False

CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173,http://localhost:5175,http://127.0.0.1:5175",
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# Email delivery configuration.
# Default backend is console for local/dev safety; switch to SMTP via env for real sending.
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
_raw_email_host = (os.getenv("EMAIL_HOST", "") or "").strip()
if _raw_email_host and "://" in _raw_email_host:
    parsed_host = urlparse(_raw_email_host).hostname or ""
    EMAIL_HOST = parsed_host.strip()
else:
    EMAIL_HOST = _raw_email_host
EMAIL_PORT = _env_int("EMAIL_PORT", 587)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip().replace(" ", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@med-questionnaire.local")
EMAIL_TIMEOUT = _env_int("EMAIL_TIMEOUT", 20)

# Patient-facing links in transactional emails (frontend origin, no trailing slash).
PATIENT_PORTAL_BASE_URL = os.getenv("PATIENT_PORTAL_BASE_URL", "").strip().rstrip("/")
EMAIL_SITE_BRAND_NAME = (os.getenv("EMAIL_SITE_BRAND_NAME", "") or "").strip() or "Med Questionnaire"

if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ValueError("EMAIL_USE_TLS and EMAIL_USE_SSL cannot both be enabled.")

# Verification code policy.
VERIFICATION_CODE_TTL_SECONDS = _env_int("VERIFICATION_CODE_TTL_SECONDS", 600)
VERIFICATION_CODE_MAX_ATTEMPTS = _env_int("VERIFICATION_CODE_MAX_ATTEMPTS", 5)
VERIFICATION_CODE_RESEND_COOLDOWN_SECONDS = _env_int("VERIFICATION_CODE_RESEND_COOLDOWN_SECONDS", 60)
# Rolling 1-hour window on EmailVerificationCode rows per email+purpose.
# DEBUG defaults to a high limit so local testing (repeated logins without trusted-device) does not lock accounts.
# Production default remains 5 unless overridden via env.
_ver_hourly_default = 100 if DEBUG else 5
VERIFICATION_CODE_MAX_REQUESTS_PER_HOUR = _env_int(
    "VERIFICATION_CODE_MAX_REQUESTS_PER_HOUR",
    _ver_hourly_default,
)

# Patient trusted device ("remember this browser") — password still required; OTP skipped until expiry.
PATIENT_TRUSTED_DEVICE_MAX_AGE_SECONDS = _env_int(
    "PATIENT_TRUSTED_DEVICE_MAX_AGE_SECONDS",
    30 * 24 * 3600,
)
PATIENT_TRUSTED_DEVICE_COOKIE_NAME = os.getenv("PATIENT_TRUSTED_DEVICE_COOKIE_NAME", "mq_patient_td")
# Used for HTTPS only: plain HTTP never sets Secure cookies (see core/trusted_device._cookie_secure).
# Typical: unset + HTTPS in production, or explicit true/false behind a reverse proxy.
PATIENT_TRUSTED_DEVICE_COOKIE_SECURE = _env_bool("PATIENT_TRUSTED_DEVICE_COOKIE_SECURE", not DEBUG)