from django.urls import path
from .api_views import (
    PatientListAPIView,
    PatientDetailAPIView,
    PatientPdfAPIView,
    PatientUpdateAPIView,
    PatientIntakeAPIView,
    PatientDeleteAPIView,
    PatientImportAPIView,
    PatientDoctorOrderAPIView,
    PatientDoctorOrderPdfAPIView,
    PatientTemplateAPIView,
    LabTemplateAPIView,
    LabImportAPIView,
    LabIndicatorListAPIView,
    QuestionnaireListAPIView,
    QuestionnaireQuestionsAPIView,
    PatientAssessmentsAPIView,
    PatientAssessmentTrendAPIView,
    AssessmentDetailAPIView,
    AssessmentRiskProfileAPIView,
    AssessmentPdfAPIView,
    PatientLabResultsAPIView,
    PatientLabTrendAPIView,
    PatientLabResultDetailAPIView,
    PatientNotesAPIView,
    PatientNoteDetailAPIView,
    PatientRiskProfileAPIView,
    PatientRiskHistoryAPIView,
    SubmitAssessmentAPIView,
)

urlpatterns = [
    path("patients/", PatientListAPIView.as_view(), name="patient_list_api"),
    path("patients/import/", PatientImportAPIView.as_view(), name="patient_import_api"),
    path("patients/template/", PatientTemplateAPIView.as_view(), name="patient_template_api"),
    path("labs/indicators/", LabIndicatorListAPIView.as_view(), name="lab_indicator_list_api"),
    path("labs/template/", LabTemplateAPIView.as_view(), name="lab_template_api"),
    path("labs/import/", LabImportAPIView.as_view(), name="lab_import_api"),
    path("patients/<int:pk>/", PatientDetailAPIView.as_view(), name="patient_detail_api"),
    path("patients/<int:pk>/pdf/", PatientPdfAPIView.as_view(), name="patient_pdf_api"),
    path("patients/<int:pk>/update/", PatientUpdateAPIView.as_view(), name="patient_update_api"),
    path("patients/<int:pk>/intake/", PatientIntakeAPIView.as_view(), name="patient_intake_api"),
    path(
        "patients/<int:patient_id>/doctor-order/",
        PatientDoctorOrderAPIView.as_view(),
        name="patient_doctor_order_api",
    ),
    path(
        "patients/<int:patient_id>/doctor-order/pdf/",
        PatientDoctorOrderPdfAPIView.as_view(),
        name="patient_doctor_order_pdf_api",
    ),
    path("patients/<int:pk>/delete/", PatientDeleteAPIView.as_view(), name="patient_delete_api"),
    path("questionnaires/", QuestionnaireListAPIView.as_view(), name="questionnaire_list_api"),
    path(
        "questionnaires/<int:questionnaire_id>/questions/",
        QuestionnaireQuestionsAPIView.as_view(),
        name="questionnaire_questions_api",
    ),
    path(
        "patients/<int:patient_id>/assessments/",
        PatientAssessmentsAPIView.as_view(),
        name="patient_assessments_api",
    ),
    path(
        "patients/<int:patient_id>/assessment-trend/",
        PatientAssessmentTrendAPIView.as_view(),
        name="patient_assessment_trend_api",
    ),
    path("assessments/<int:pk>/", AssessmentDetailAPIView.as_view(), name="assessment_detail_api"),
    path("assessments/<int:pk>/risk/", AssessmentRiskProfileAPIView.as_view(), name="assessment_risk_api"),
    path("assessments/<int:pk>/pdf/", AssessmentPdfAPIView.as_view(), name="assessment_pdf_api"),
    path(
        "patients/<int:patient_id>/labs/",
        PatientLabResultsAPIView.as_view(),
        name="patient_labs_api",
    ),
    path(
        "patients/<int:patient_id>/lab-trend/",
        PatientLabTrendAPIView.as_view(),
        name="patient_lab_trend_api",
    ),
    path(
        "patients/<int:patient_id>/labs/<int:lab_result_id>/",
        PatientLabResultDetailAPIView.as_view(),
        name="patient_lab_result_detail_api",
    ),
    path(
        "patients/<int:patient_id>/notes/",
        PatientNotesAPIView.as_view(),
        name="patient_notes_api",
    ),
    path(
        "patients/<int:patient_id>/notes/<int:note_id>/",
        PatientNoteDetailAPIView.as_view(),
        name="patient_note_detail_api",
    ),
    path(
        "patients/<int:patient_id>/risk-profile/",
        PatientRiskProfileAPIView.as_view(),
        name="patient_risk_profile_api",
    ),
    path(
        "patients/<int:patient_id>/risk-history/",
        PatientRiskHistoryAPIView.as_view(),
        name="patient_risk_history_api",
    ),
    path("assessments/submit/", SubmitAssessmentAPIView.as_view(), name="submit_assessment_api"),
]