from django.urls import path
from .api_views import (
    PatientListAPIView,
    PatientDetailAPIView,
    PatientAccountLinkAPIView,
    PatientPdfAPIView,
    PatientUpdateAPIView,
    PatientIntakeAPIView,
    PatientDeleteAPIView,
    PatientImportAPIView,
    PatientDoctorOrderAPIView,
    PatientDoctorOrderPdfAPIView,
    PatientTemplateAPIView,
    LabTemplateAPIView,
    LabImportAPIView,
    LabIndicatorListAPIView,
    DiseaseListAPIView,
    QuestionnaireListAPIView,
    QuestionnaireQuestionsAPIView,
    PatientAssessmentsAPIView,
    PatientAssessmentTrendAPIView,
    AssessmentDetailAPIView,
    AssessmentRiskProfileAPIView,
    AssessmentPdfAPIView,
    PatientLabResultsAPIView,
    PatientLabTrendAPIView,
    PatientLabResultDetailAPIView,
    PatientNotesAPIView,
    PatientNoteDetailAPIView,
    PatientRiskProfileAPIView,
    PatientRiskHistoryAPIView,
    SubmitAssessmentAPIView,
    QuestionnaireDetailAPIView,
    SubmitQuestionnaireForApprovalAPIView,
    PendingQuestionnairesAPIView,
    ArchivedQuestionnairesAPIView,
    RestoreQuestionnaireAPIView,
    ApproveQuestionnaireAPIView,
    RejectQuestionnaireAPIView,
    RequestQuestionnaireChangesAPIView,
    QuestionnaireSessionCreateAPIView,
    PublicQuestionnaireAPIView,
    PublicQuestionnaireSubmitAPIView,
    DashboardStatsAPIView,
    AuditLogListAPIView,
    UserRoleListAPIView,
    AssignUserRoleAPIView,
    QuestionnaireSessionListAPIView,
)

urlpatterns = [
    path("patients/", PatientListAPIView.as_view(), name="patient_list_api"),
    path("patients/import/", PatientImportAPIView.as_view(), name="patient_import_api"),
    path("patients/template/", PatientTemplateAPIView.as_view(), name="patient_template_api"),
    path("labs/indicators/", LabIndicatorListAPIView.as_view(), name="lab_indicator_list_api"),
    path("diseases/", DiseaseListAPIView.as_view(), name="disease_list_api"),
    path("labs/template/", LabTemplateAPIView.as_view(), name="lab_template_api"),
    path("labs/import/", LabImportAPIView.as_view(), name="lab_import_api"),
    path("patients/<int:pk>/", PatientDetailAPIView.as_view(), name="patient_detail_api"),
    path("patients/<int:patient_id>/link-user/", PatientAccountLinkAPIView.as_view(), name="patient_link_user_api"),
    path("patients/<int:pk>/pdf/", PatientPdfAPIView.as_view(), name="patient_pdf_api"),
    path("patients/<int:pk>/update/", PatientUpdateAPIView.as_view(), name="patient_update_api"),
    path("patients/<int:pk>/intake/", PatientIntakeAPIView.as_view(), name="patient_intake_api"),
    path(
        "patients/<int:patient_id>/doctor-order/",
        PatientDoctorOrderAPIView.as_view(),
        name="patient_doctor_order_api",
    ),
    path(
        "patients/<int:patient_id>/doctor-order/pdf/",
        PatientDoctorOrderPdfAPIView.as_view(),
        name="patient_doctor_order_pdf_api",
    ),
    path("patients/<int:pk>/delete/", PatientDeleteAPIView.as_view(), name="patient_delete_api"),
    path("questionnaires/", QuestionnaireListAPIView.as_view(), name="questionnaire_list_api"),
    path("questionnaires/<int:pk>/", QuestionnaireDetailAPIView.as_view(), name="questionnaire_detail_api"),
    path(
        "questionnaires/<int:pk>/submit-for-approval/",
        SubmitQuestionnaireForApprovalAPIView.as_view(),
        name="questionnaire_submit_for_approval_api",
    ),
    path(
        "questionnaires/pending-approval/",
        PendingQuestionnairesAPIView.as_view(),
        name="questionnaire_pending_approval_api",
    ),
    path(
        "questionnaires/archived/",
        ArchivedQuestionnairesAPIView.as_view(),
        name="questionnaire_archived_api",
    ),
    path(
        "questionnaires/<int:pk>/restore/",
        RestoreQuestionnaireAPIView.as_view(),
        name="questionnaire_restore_api",
    ),
    path("questionnaires/<int:pk>/approve/", ApproveQuestionnaireAPIView.as_view(), name="questionnaire_approve_api"),
    path("questionnaires/<int:pk>/reject/", RejectQuestionnaireAPIView.as_view(), name="questionnaire_reject_api"),
    path(
        "questionnaires/<int:pk>/request-changes/",
        RequestQuestionnaireChangesAPIView.as_view(),
        name="questionnaire_request_changes_api",
    ),
    path(
        "questionnaires/<int:questionnaire_id>/questions/",
        QuestionnaireQuestionsAPIView.as_view(),
        name="questionnaire_questions_api",
    ),
    path(
        "patients/<int:patient_id>/assessments/",
        PatientAssessmentsAPIView.as_view(),
        name="patient_assessments_api",
    ),
    path(
        "patients/<int:patient_id>/assessment-trend/",
        PatientAssessmentTrendAPIView.as_view(),
        name="patient_assessment_trend_api",
    ),
    path("assessments/<int:pk>/", AssessmentDetailAPIView.as_view(), name="assessment_detail_api"),
    path("assessments/<int:pk>/risk/", AssessmentRiskProfileAPIView.as_view(), name="assessment_risk_api"),
    path("assessments/<int:pk>/pdf/", AssessmentPdfAPIView.as_view(), name="assessment_pdf_api"),
    path(
        "patients/<int:patient_id>/labs/",
        PatientLabResultsAPIView.as_view(),
        name="patient_labs_api",
    ),
    path(
        "patients/<int:patient_id>/lab-trend/",
        PatientLabTrendAPIView.as_view(),
        name="patient_lab_trend_api",
    ),
    path(
        "patients/<int:patient_id>/labs/<int:lab_result_id>/",
        PatientLabResultDetailAPIView.as_view(),
        name="patient_lab_result_detail_api",
    ),
    path(
        "patients/<int:patient_id>/notes/",
        PatientNotesAPIView.as_view(),
        name="patient_notes_api",
    ),
    path(
        "patients/<int:patient_id>/notes/<int:note_id>/",
        PatientNoteDetailAPIView.as_view(),
        name="patient_note_detail_api",
    ),
    path(
        "patients/<int:patient_id>/risk-profile/",
        PatientRiskProfileAPIView.as_view(),
        name="patient_risk_profile_api",
    ),
    path(
        "patients/<int:patient_id>/risk-history/",
        PatientRiskHistoryAPIView.as_view(),
        name="patient_risk_history_api",
    ),
    path("assessments/submit/", SubmitAssessmentAPIView.as_view(), name="submit_assessment_api"),
    path("dashboard/stats/", DashboardStatsAPIView.as_view(), name="dashboard_stats_api"),
    path("audit-logs/", AuditLogListAPIView.as_view(), name="audit_log_list_api"),
    path("users/roles/", UserRoleListAPIView.as_view(), name="user_role_list_api"),
    path("users/<int:user_id>/assign-role/", AssignUserRoleAPIView.as_view(), name="assign_user_role_api"),
    path("questionnaire-sessions/", QuestionnaireSessionCreateAPIView.as_view(), name="questionnaire_session_create_api"),
    path("questionnaire-sessions/list/", QuestionnaireSessionListAPIView.as_view(), name="questionnaire_session_list_api"),
    path("public/questionnaire/<str:token>/", PublicQuestionnaireAPIView.as_view(), name="public_questionnaire_api"),
    path(
        "public/questionnaire/<str:token>/submit/",
        PublicQuestionnaireSubmitAPIView.as_view(),
        name="public_questionnaire_submit_api",
    ),
]