# Generated by Django 6.0.2 on 2026-02-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_labindicator_labresult_labvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='labindicator',
            name='category',
            field=models.CharField(choices=[('mineral', 'Mineral'), ('hormone', 'Hormone'), ('vitamin', 'Vitamin'), ('other', 'Other')], default='other', max_length=20),
            preserve_default=False,
        ),
    ]
