# Generated by Django 6.0.2 on 2026-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_labindicator_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Patient ID'),
        ),
    ]
