# Generated by Django 6.0.4 on 2026-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patientnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='text_kk',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ru',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_kk',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_ru',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='title_kk',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
