# Generated by Django 6.0.4 on 2026-04-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_question_text_en_question_text_kk_question_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('stable', 'Stable'), ('monitoring', 'Monitoring'), ('attention', 'Attention'), ('critical', 'Critical')], default='monitoring', max_length=20),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('visit', 'Visit'), ('treatment', 'Treatment'), ('lab', 'Lab')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='patientnote',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
