# Generated by Django 6.0.4 on 2026-04-16 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patient_next_visit_date_patient_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnote',
            name='category',
            field=models.CharField(choices=[('complaints', 'Complaints'), ('diagnosis', 'Diagnosis'), ('recommendations', 'Recommendations'), ('general', 'General'), ('visit', 'Visit'), ('treatment', 'Treatment'), ('lab', 'Lab')], default='general', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='patientnote',
            constraint=models.UniqueConstraint(condition=models.Q(('pinned', True)), fields=('patient',), name='unique_pinned_note_per_patient'),
        ),
    ]
