# Generated by Django 6.0.4 on 2026-04-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_doctorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="completion_percent",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="assessment",
            name="interpretation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="assessment",
            name="quality_flag",
            field=models.CharField(
                choices=[("valid", "Valid"), ("partial", "Partial"), ("invalid", "Invalid")],
                default="valid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="interpretation_schema",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="kind",
            field=models.CharField(
                choices=[("screening", "Screening"), ("severity", "Severity"), ("followup", "Follow-up")],
                default="screening",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="min_completion_percent",
            field=models.PositiveSmallIntegerField(default=70),
        ),
        migrations.AddField(
            model_name="questionnaire",
            name="target_condition_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
