# Generated by Django 6.0.4 on 2026-04-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_questionnaire_medlogic_and_assessment_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="labindicator",
            name="code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="labindicator",
            name="standard_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="labindicator",
            name="synonyms",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="labindicator",
            name="category",
            field=models.CharField(
                choices=[
                    ("metabolic", "Metabolic"),
                    ("cardiovascular", "Cardiovascular"),
                    ("inflammation", "Inflammation"),
                    ("anemia", "Anemia"),
                    ("renal", "Renal"),
                    ("hepatic", "Hepatic"),
                    ("mineral", "Mineral"),
                    ("hormone", "Hormone"),
                    ("vitamin", "Vitamin"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="feature_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="question",
            name="red_flag_level",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="question",
            name="red_flag_message",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.CreateModel(
            name="RecommendationTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template_id", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("preliminary_conclusion", models.TextField()),
                ("next_steps", models.TextField()),
                (
                    "disclaimer",
                    models.TextField(
                        default="Clinical decision support only. This output is not a final diagnosis."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PatientRiskProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overall_risk_level", models.CharField(default="low", max_length=20)),
                ("summary", models.TextField(blank=True, default="")),
                ("profile_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_profiles",
                        to="core.assessment",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_profiles",
                        to="core.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskRedFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("urgency_level", models.CharField(max_length=20)),
                ("trigger_signs", models.JSONField(blank=True, default=list)),
                ("recommended_action", models.TextField()),
                (
                    "risk_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="red_flags",
                        to="core.patientriskprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskFinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("problem_code", models.CharField(max_length=64)),
                ("risk_level", models.CharField(max_length=20)),
                ("evidence", models.JSONField(blank=True, default=list)),
                ("ml_probability", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "recommendation_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.recommendationtemplate",
                    ),
                ),
                (
                    "risk_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="core.patientriskprofile",
                    ),
                ),
            ],
        ),
    ]
