# Generated by Django 5.2.13 on 2026-04-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_doctorprofile_compact_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='role',
            field=models.CharField(choices=[('pending', 'Pending'), ('patient', 'Patient'), ('doctor', 'Doctor'), ('chief_doctor', 'Chief doctor')], default='pending', max_length=32),
        ),
    ]
