# Generated by Django 5.2.13 on 2026-04-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_patient_email_alter_answer_id_alter_assessment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('patient_signup', 'Patient signup'), ('doctor_signup', 'Doctor signup')], max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email', 'purpose', '-created_at'], name='core_emailv_email_fbf24c_idx'), models.Index(fields=['expires_at'], name='core_emailv_expires_53c990_idx')],
            },
        ),
    ]
