# Generated by Django 5.2.13 on 2026-05-02 13:24

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_questionnaire_assignment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="questionnaireassignment",
            constraint=models.UniqueConstraint(
                condition=Q(status__in=["assigned", "in_progress"]),
                fields=("patient", "questionnaire"),
                name="core_qassign_uniq_active_patient_questionnaire",
            ),
        ),
    ]
